### PR TITLE
100.8.0

### PR DESCRIPTION
**Pull request by tschie**
Release for 100.8.0 including the new feature template picker control.

### CODE REVIEW

**Comment by tdillon** [comment]
Is there any update on the next toolkit release?  FXML support from https://github.com/Esri/arcgis-runtime-toolkit-java/pull/23 would be nice.

**Comment by mbcoder** [comment]
@tdillon although we've not made is available in a built release available as a jar from our Maven server, you can pull this code and built it yourself to use the latest fixes and functionality.  The toolkit is open source.

**Comment by tdillon** [comment]
@mbcoder I did build the jar locally to test Scene Builder, but that isn't practical for CI/CD.  Are there any plans for new versions of this repo to be published to your Maven server?

**Comment by dwhitla** [comment]
Is there an answer to @tdillon 's question yet? Forking your repo and checking for updates to build and deploy to our own maven repo is a major PITA when all this project needs to do is release from its own CI/CD pipeline as features are merged to master.

**Comment by jenmerritt** [comment]
Closing this PR - we'll be creating an updated release of the toolkit alongside the 100.14.0 release of the ArcGIS Runtime SDK for Java (due Spring 2022). The toolkit jar will be made available via our maven repository on jfrog. Additional information will be provided at that time, but this will include new toolkit components as well as updates and improvements to existing components, including #23 mentioned above. 
Thanks for your feedback regarding CI/CD - it's been noted as we work on a plan for maintaining the toolkit going forward.

**Pull request closed without merging**
